version: "3.4"                                                                                                        
                                                                                                                      
x-defaults: &defaults                                                                                                 
  restart: unless-stopped                                                                                             

services:
  quix_sdk:
    build:
      context: ..
      dockerfile: ./PythonClient/Dockerfile
#    env_file:
#     - ./.env
    depends_on:
      - kafka
    networks:
      - kafka
    volumes:
      - ../:/app  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - zookeeper
      - kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
networks:
  zookeeper:
    driver: bridge
  kafka:
    driver: bridge
