# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: root.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'root.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import nested_pb2 as nested__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroot.proto\x12\nschemas.v1\x1a\x0cnested.proto\"f\n\x04Root\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12 \n\x04\x65num\x18\x03 \x01(\x0e\x32\x12.schemas.v1.Letter\x12\"\n\x06nested\x18\x04 \x01(\x0b\x32\x12.schemas.v1.Nested*\x16\n\x06Letter\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'root_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LETTER']._serialized_start=144
  _globals['_LETTER']._serialized_end=166
  _globals['_ROOT']._serialized_start=40
  _globals['_ROOT']._serialized_end=142
# @@protoc_insertion_point(module_scope)
