repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: conda-requirements
        name: conda-requirements
        entry: python conda/requirements.py
        language: python
        files: ^(requirements\.txt|pyproject\.toml)$
