# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test_quixstreams/test_models/protobuf/test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n6tests/test_quixstreams/test_models/protobuf/test.proto\x12\x04test">\n\x04Test\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x1c\n\x04\x65num\x18\x03 \x01(\x0e\x32\x0e.test.TestEnum*\x18\n\x08TestEnum\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x62\x06proto3'
)

_TESTENUM = DESCRIPTOR.enum_types_by_name["TestEnum"]
TestEnum = enum_type_wrapper.EnumTypeWrapper(_TESTENUM)
A = 0
B = 1


_TEST = DESCRIPTOR.message_types_by_name["Test"]
Test = _reflection.GeneratedProtocolMessageType(
    "Test",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEST,
        "__module__": "tests.test_quixstreams.test_models.protobuf.test_pb2",
        # @@protoc_insertion_point(class_scope:test.Test)
    },
)
_sym_db.RegisterMessage(Test)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _TESTENUM._serialized_start = 128
    _TESTENUM._serialized_end = 152
    _TEST._serialized_start = 64
    _TEST._serialized_end = 126
# @@protoc_insertion_point(module_scope)
