# Versions before this (such as `manylinux2014_aarch64`) don't have the necessary glibcxx (3.4.20 and some higher). See https://access.redhat.com/discussions/6886591 for more
FROM ubuntu:focal-20230301

#ARG PYVER=3.11.0
ARG PYVER=3.8.10
ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

RUN apt-get update && \
    apt-get install -y curl build-essential checkinstall && \
    apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev

    
WORKDIR python
RUN curl https://www.python.org/ftp/python/$PYVER/Python-$PYVER.tgz --output python-$PYVER.tgz
RUN tar xzf python-$PYVER.tgz
WORKDIR /python/Python-$PYVER
RUN ./configure --prefix=/python/build-result --enable-optimizations --enable-shared
RUN make install

COPY python_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/bin/bash", "-i", "/entrypoint.sh"]