# Not using `manylinux1` because of lack of dotnet support
FROM --platform=linux/amd64 quay.io/pypa/manylinux2014_x86_64

RUN yum install clang gcc krb5-devel libstdc++-static python3 -y

RUN echo "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"  >> ~/.bashrc
RUN curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --version 7.0.102 && \
    echo "export DOTNET_ROOT=$HOME/.dotnet" >> ~/.bashrc && \
    echo "export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools" >> ~/.bashrc

RUN python3 -m pip install wheel

COPY whl_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/bin/bash", "-i", "/entrypoint.sh"]