# Versions before this (such as `manylinux2014_aarch64`) don't have the necessary glibcxx (3.4.20 and some higher). See https://access.redhat.com/discussions/6886591 for more
FROM --platform=linux/arm64 quay.io/pypa/manylinux_2_28_aarch64

RUN yum install clang gcc krb5-devel libstdc++-static python3 -y

RUN echo "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"  >> ~/.profile
RUN curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
#    ./dotnet-install.sh --channel 8.0.1xx --quality preview && \
    ./dotnet-install.sh --version 8.0.100-preview.2.23157.25 && \
    echo "export DOTNET_ROOT=$HOME/.dotnet" >> ~/.profile && \
    echo "export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools" >> ~/.profile

RUN python3 -m pip install wheel

COPY entrypoint.py /entrypoint.py

ENTRYPOINT ["/bin/sh", "-l", "-c", "python3 /entrypoint.py"]