package:
  name: quixstreams
  version: {{ QUIXSTREAMS_VERSION }}

source:
  git_url: https://github.com/quixio/quix-streams
  git_tag: v{{ QUIXSTREAMS_VERSION }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation .

requirements:
  host:
    - python >=3.9,<3.13
  run:
    - python >=3.9,<3.13
    - requests >=2.32
    - typing_extensions >=4.8
    - orjson >=3.9,<4
    - pydantic >=2.7,<2.12
    - pydantic-settings >=2.3,<2.9
    - jsonschema >=4.3.0
    - fastavro >=1.8,<2.0
    - jsonlines >=4,<5
    - google-cloud-bigquery >=3.26.0,<3.27
    - google-cloud-pubsub >=2.23.1,<3
    - psycopg2-binary >=2.9.9,<3
    - boto3 >=1.35.65,<2.0
    - boto3-stubs >=1.35.65,<2.0
    - azure-storage-blob >=12.24.0,<12.25
    - neo4j-python-driver >=5.27.0,<6
    - pymongo >=4.11,<5
    - pandas >=1.0.0,<3.0
    - elasticsearch >=8.17,<9
    - rich >=13,<14

test:
  imports:
    - quixstreams

about:
  home: https://quix.io
  summary: Python library for building stream processing applications with Apache Kafka
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://quix.io/docs/quix-streams/introduction.html
  dev_url: https://github.com/quixio/quix-streams
