from quixstreams.exceptions import QuixException


class PartitionNotAssignedError(QuixException): ...


class PartitionStoreIsUsed(QuixException): ...


class StoreNotRegisteredError(QuixException): ...


class WindowedStoreAlreadyRegisteredError(QuixException): ...


class InvalidStoreTransactionStateError(QuixException): ...


class StoreTransactionFailed(QuixException): ...


class InvalidStoreChangelogOffset(QuixException): ...


class StateError(QuixException): ...


class StateSerializationError(StateError): ...


class StateTransactionError(StateError): ...


class ColumnFamilyHeaderMissing(StateError): ...


class ColumnFamilyDoesNotExist(StateError): ...


class InvalidChangelogOffset(StateError): ...


class ChangelogTopicPartitionNotAssigned(QuixException): ...
