name: Generate Documentation

on:
  push:
    branches:
      - autogenerate-docs

permissions: { }

jobs:
  generate-docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r docs/build/requirements.txt
      - run: python build.py
        working-directory: ./docs/build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update documentation
          branch: update-docs
          delete-branch: true
          title: 'Update Documentation'
          body: 'This PR updates the documentation with the latest changes.'
          labels: 'documentation'
