name: '[Streaming DataFrames] Tests'

on:
  push:
    paths:
      - 'src/StreamingDataFrames/**'
  pull_request:
    paths:
      - 'src/StreamingDataFrames/**'

defaults:
  run:
    working-directory: 'src/StreamingDataFrames'

# Run only one workflow per PR or commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

# Disable default permissions for all jobs
permissions: { }

jobs:
  lint:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install linters
        run: |
          python -m pip install -U -r requirements-dev.txt
      - name: Run Black
        run: |
          python -m black --check streamingdataframes
          python -m black --check tests

  test:
    needs: lint
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Run Python tests (python${{ matrix.python }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python: [ 3.11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Update pip
        run: |
          python -m pip install -U pip
      - name: Install requirements
        run: |
          python -m pip install -U -r tests/requirements.txt
          python -m pip install -U -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -s -v
